### ISSUE TITLE
Notifications not being sent?

### ISSUE THREAD

**Issue by chocolateboy** [andreausu/git-notifier#18]
I'm missing a few notifications (every event, daily) for projects that have been starred over the past few weeks. The notifications appear correctly on the [website](https://gitnotifier.io). My contact email address is working and receiving mail, and I can't find the missing notifications in my spam folder.

Is there an issue sending emails?

**Comment by amitness** [comment]
I've the same issue. I updated my github username and email address few days back and from then, I'm not receiving any updates either on mail or the website. I've tried revoking access to gitnotifier and reconnecting, but still the issue persists.

**Comment by andreausu** [comment]
Hi @chocolateboy apologies about the late response, is the issue still persisting? If so, could you please provide me with some examples so I can check the logs?

@amitess your issue doesn't seem to be related, could you please try to login again now?

**Comment by chocolateboy** [comment]
@andreausu Thanks for looking into it. I'm not exactly sure when I stopped receiving them but it looks like I haven't been notified of the most recent starrings in these repos:

* https://github.com/chocolateboy/userscripts/stargazers
* https://github.com/chocolateboy/shell-escape-tag/stargazers

It's possible my [mail host is silently filtering them](http://blogs.perl.org/users/peter_rabbitson/2014/09/how-does-emailcpanorg-work.html), but they worked before, and I haven't noticed any other emails to that address going AWOL.

**Comment by chocolateboy** [comment]
Closing this as it has suddenly started working again :-)
