### ISSUE TITLE
I selected daily emails, but I get ASAP

### ISSUE THREAD

**Issue by IonicaBizau** [andreausu/git-notifier#9]
...probably related to the latest changes.

**Comment by rs** [comment]
same here

**Comment by IonicaBizau** [comment]
It spammed me all day, lol. :smile:

**Comment by IonicaBizau** [comment]
@andreausu Man, please do something. :smile_cat: I like this project, but I only want to get one email a day... :grin:

**Comment by andreausu** [comment]
I'm investigating now, sorry about that!

**Comment by IonicaBizau** [comment]
@andreausu Thanks :smile:

**Comment by andreausu** [comment]
I’ve prevented wrong emails from going out so you should not be receiving them anymore. Now I’m working to fix the root cause :)

**Comment by IonicaBizau** [comment]
Thanks, @andreausu! :apple:

**Comment by andreausu** [comment]
This will prevent the same issue from happening again in the future: https://github.com/andreausu/git-notifier/commit/c48434055c75aa8ea420b42ebb9e06c0a4c38846

Thank you for reporting this and sorry about the annoying emails!

**Comment by IonicaBizau** [comment]
@andreausu Thanks for the fix. Are the things stable again?

**Comment by andreausu** [comment]
Yes :)
